"""restore_missing_drive_tables

Revision ID: e4286b21a303
Revises: a174cabbfc07
Create Date: 2026-01-26 17:36:31.210277

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4286b21a303'
down_revision = 'a174cabbfc07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('_alembic_tmp_drive_file')
    with op.batch_alter_table('drive_file', schema=None) as batch_op:
        batch_op.alter_column('drive_folder_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('filename',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=512),
               existing_nullable=False)
        batch_op.alter_column('encrypted_path',
               existing_type=sa.VARCHAR(length=1000),
               type_=sa.String(length=512),
               existing_nullable=True)
        batch_op.alter_column('file_hash',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=64),
               existing_nullable=True)
        batch_op.alter_column('file_size',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.drop_column('ocr_error')
        batch_op.drop_column('auto_mapped')
        batch_op.drop_column('parent_folder_name')
        batch_op.drop_column('ocr_completed')

    with op.batch_alter_table('drive_file_content', schema=None) as batch_op:
        batch_op.alter_column('content_text',
               existing_type=sa.TEXT(),
               nullable=False)

    with op.batch_alter_table('drive_folder', schema=None) as batch_op:
        batch_op.add_column(sa.Column('class_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('folder_id', sa.String(length=256), nullable=False))
        batch_op.add_column(sa.Column('file_count', sa.Integer(), nullable=True))
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('folder_name',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=256),
               existing_nullable=False)
        # batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_drive_folder_class_id', 'school_class', ['class_id'], ['id'])
        batch_op.drop_column('created_at')
        batch_op.drop_column('sync_enabled')
        batch_op.drop_column('privacy_level')
        batch_op.drop_column('parent_id')
        batch_op.drop_column('drive_folder_id')
        batch_op.drop_column('folder_path')
        batch_op.drop_column('is_root')
        batch_op.drop_column('sync_error')
        batch_op.drop_column('sync_status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('drive_folder', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sync_status', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('sync_error', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('is_root', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('folder_path', sa.VARCHAR(length=1000), nullable=True))
        batch_op.add_column(sa.Column('drive_folder_id', sa.VARCHAR(length=256), nullable=False))
        batch_op.add_column(sa.Column('parent_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('privacy_level', sa.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('sync_enabled', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DATETIME(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'drive_folder', ['parent_id'], ['id'])
        batch_op.alter_column('folder_name',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=500),
               existing_nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('file_count')
        batch_op.drop_column('folder_id')
        batch_op.drop_column('class_id')

    with op.batch_alter_table('drive_file_content', schema=None) as batch_op:
        batch_op.alter_column('content_text',
               existing_type=sa.TEXT(),
               nullable=True)

    with op.batch_alter_table('drive_file', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ocr_completed', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('parent_folder_name', sa.VARCHAR(length=512), nullable=True))
        batch_op.add_column(sa.Column('auto_mapped', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('ocr_error', sa.TEXT(), nullable=True))
        batch_op.alter_column('file_size',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
        batch_op.alter_column('file_hash',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=128),
               existing_nullable=True)
        batch_op.alter_column('encrypted_path',
               existing_type=sa.String(length=512),
               type_=sa.VARCHAR(length=1000),
               existing_nullable=True)
        batch_op.alter_column('filename',
               existing_type=sa.String(length=512),
               type_=sa.VARCHAR(length=500),
               existing_nullable=False)
        batch_op.alter_column('drive_folder_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    op.create_table('_alembic_tmp_drive_file',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('drive_folder_id', sa.INTEGER(), nullable=False),
    sa.Column('file_id', sa.VARCHAR(length=256), nullable=False),
    sa.Column('filename', sa.VARCHAR(length=512), nullable=False),
    sa.Column('mime_type', sa.VARCHAR(length=128), nullable=True),
    sa.Column('file_size', sa.INTEGER(), nullable=True),
    sa.Column('file_hash', sa.VARCHAR(length=64), nullable=True),
    sa.Column('encrypted_path', sa.VARCHAR(length=512), nullable=True),
    sa.Column('subject_id', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['drive_folder_id'], ['drive_folder.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subject.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_id')
    )
    # ### end Alembic commands ###
